import Head from "next/head";
import { API_URL, MOMENTS_ROUTE } from "../../common/api/constants";
import Header from "../../components/Header";
import MemorableMoments from "../../components/MemorableMoments";

const MemorableMomentsPage = ({ moments }) => {
    return (
        <>
            <Head>
                <title>RMIT FinTech Club SGS | Memorable Moments</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>
            <Header />
            <div className="container">
                <h1 className="text-center display-3 pt-5">Memorable Moments</h1>
                <MemorableMoments moments={moments} />
            </div>
        </>
    );
};

export async function getStaticProps() {
    let moments = [];
    try {
        const res = await fetch(API_URL + MOMENTS_ROUTE);
        moments = await res.json();
    } catch (e) {
        console.log(e);
    }
    return {
        props: {
            moments,
        },
        revalidate: 60,
    };
}

export default MemorableMomentsPage;
