import Head from "next/head";
import Header from "../../components/Header";
import MemorableMoments from "../../components/MemorableMoments";

const MemorableMomentsPage = () => {
    return (
        <>
            <Head>
                <title>Memorable Moments</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>
            <Header />
            <div className="container">
                <h1 className="text-center display-3 pt-5">Memorable Moments</h1>
                <MemorableMoments />
            </div>
        </>
    );
};

export default MemorableMomentsPage;
