import Head from "next/head";
import { API_URL, MOMENTS_ROUTE } from "../../common/api/constants";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import MemorableMoments from "../../components/MemorableMoments";
import { smartFetch } from "../../common/utils";

const MemorableMomentsPage = ({ moments }) => {
    moments = moments || [];
    return (
        <>
            <Head>
                <title>RMIT FinTech Club SGS | Memorable Moments</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>
            <Header />
            <div className="container">
                <div className="d-flex justify-content-center">
                    <h1 className="text-center display-3 mt-5 page-title">Memorable Moments</h1>
                </div>
                <MemorableMoments moments={moments} />
            </div>
            <Footer />
        </>
    );
};

export async function getStaticProps() {
    const moments = await smartFetch(API_URL + MOMENTS_ROUTE);

    return {
        props: {
            moments,
        },
        revalidate: 60,
    };
}

export default MemorableMomentsPage;
