import Head from "next/head";
import Header from "../../components/Header";
import Departments from "../../components/about-us/Departments";
import Members from "../../components/about-us/AllMembers";
import { API_URL, DEPARTMENTS_ROUTE } from "../../common/api/constants";

export default function AboutUs({ departmentsInfo }) {
    return (
        <>
            <Head>
                <title>RMIT FinTech Club SGS | About Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>
            <Header />
            <div className="">
                <h1 className="text-center display-3 pt-5">About Us</h1>
                <Departments departmentsInfo={departmentsInfo} />
                <Members />
            </div>
        </>
    );
}

export async function getStaticProps() {
    const res = await fetch(API_URL + DEPARTMENTS_ROUTE);
    const departmentsInfo = await res.json();
    return {
        props: {
            departmentsInfo,
        },
        revalidate: 60,
    };
}
