import Head from "next/head";
import Header from "../../components/Header";
import Departments from "../../components/about-us/Departments";
import Members from "../../components/about-us/AllMembers";

export default function AboutUs() {
    return (
        <>
            <Head>
                <title>RMIT Fintech Club SGS | About us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.png" />
            </Head>
            <Header />
            <div className="">
                <h1 className="text-center display-3 pt-5">About Us</h1>
                <Departments />
                <Members />
            </div>
        </>
    );
}
