import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Welcome from '../components/Welcome'
import UpcomingEvents from '../components/UpcomingEvents'
import Vision from '../components/Vision'


export default function Home() {
  return (
    <>
      <Head>
        <title>RMIT Fintech Club SGS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Header/>
      <div className='container'>
      <Welcome/>
      <UpcomingEvents/>
      <Vision/>
      </div>
      

    </>
  )
}
